#ifndef GUARD_DIFFICULTY_CONSTANTS_H
#define GUARD_DIFFICULTY_CONSTANTS_H

enum DifficultyLevel
{
    DIFFICULTY_WORLD_ZERO,
    DIFFICULTY_WORLD_ONE,
    DIFFICULTY_WORLD_TWO,
    DIFFICULTY_WORLD_THREE,
    DIFFICULTY_WORLD_FOUR,
    DIFFICULTY_WORLD_FIVE,
    DIFFICULTY_WORLD_SIX,
    DIFFICULTY_WORLD_SEVEN,
    DIFFICULTY_WORLD_EIGHT,
    DIFFICULTY_WORLD_NINE,
    DIFFICULTY_WORLD_TEN,
    DIFFICULTY_WORLD_ELEVEN,
    DIFFICULTY_EASY,
    DIFFICULTY_NORMAL, //If you rename this, the word "Normal" in fprint_trainers must be replaced with the new difficulty name.
    DIFFICULTY_HARD,
    DIFFICULTY_COUNT,
};

#define DIFFICULTY_MIN 0
#define DIFFICULTY_MAX (DIFFICULTY_COUNT - 1)

#endif // GUARD_DIFFICULTY_CONSTANTS_H
